---
all:
  children:
    kafka:
      hosts:
        kafka-1:
          ansible_host: 10.10.10.11
          kafka_broker_id: 1
          kafka_internal_ip: 10.10.10.11
          kafka_external_ip: 198.51.100.21
        kafka-2:
          ansible_host: 10.10.10.12
          kafka_broker_id: 2
          kafka_internal_ip: 10.10.10.12
          kafka_external_ip: 198.51.100.22
        kafka-3:
          ansible_host: 10.10.10.13
          kafka_broker_id: 3
          kafka_internal_ip: 10.10.10.13
          kafka_external_ip: 198.51.100.23
    zookeeper:
      hosts:
        zk-1:
          ansible_host: 10.10.20.11
          zookeeper_id: 1
        zk-2:
          ansible_host: 10.10.20.12
          zookeeper_id: 2
        zk-3:
          ansible_host: 10.10.20.13
          zookeeper_id: 3
    console:
      hosts:
        console-1:
          ansible_host: 10.10.30.10
    pfsense_docs:
      hosts:
        localhost:
          ansible_connection: local
