---
docker_project_dir: /opt/kafka-lab
docker_compose_file: docker-compose.yml

dev_kafka_image: bitnami/kafka:3.8
dev_zookeeper_image: bitnami/zookeeper:3.9
dev_console_image: docker.redpanda.com/redpandadata/console:v2.7.2
dev_node_exporter_image: prom/node-exporter:v1.8.2
dev_jmx_exporter_image: bitnami/jmx-exporter:1.0.1

kafka_external_listener_port_base: 29092
